services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    restart: always
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=direct-ip.rohitnavani.com
      - PROXY=false # Keeps the orange cloud active
      - IP6_PROVIDER=none
