#!/bin/bash

SOURCE_PATH="$1"
DEST_DIR="$2"

if [ -z "$SOURCE_PATH" ] || [ -z "$DEST_DIR" ]; then
    echo "Error: Missing arguments."
    echo "Usage: autorar <SOURCE_PATH> <DESTINATION_DIR>"
    exit 1
fi

SOURCE_PATH="$(echo "$SOURCE_PATH" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
DEST_DIR="$(echo "$DEST_DIR" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

PARENT_DIR=$(dirname "$SOURCE_PATH")
ITEM_NAME=$(basename "$SOURCE_PATH")
RAR_COMPRESSION_ARGS="-m5 -s -md512m -ma5"

mkdir -p "$DEST_DIR" && \
cd "$PARENT_DIR" && \
rar a $RAR_COMPRESSION_ARGS "$DEST_DIR/$ITEM_NAME.rar" "$ITEM_NAME" && \
echo "Successfully created \"$ITEM_NAME.rar\" in \"$DEST_DIR\"." && \
rm -rf "$SOURCE_PATH" || \
echo "Failed to create RAR archive for \"$ITEM_NAME\"."
